const FALLBACKS={Door:{width:900,height:2100,thickness:45,frameWidth:100,openingAngle:90},Window:{width:1200,height:1200,frameDepth:80,frameWidth:60,panelCount:2},Beam:{length:3000,width:200,height:400},Roof:{length:4000,width:3000,thickness:150,slope:15},ConstructionBlock:{length:390,width:190,height:190},Pipe:{length:1000,diameter:100,innerDiameter:80},Duct:{length:1000,width:400,height:250,thickness:10,ductShape:'rectangular'},Furniture:{width:600,depth:600,height:900},Fixture:{width:600,depth:600,height:900},Foundation:{length:1500,width:1500,height:500},Vegetation:{height:3000,diameter:1500},GenericBIMObject:{width:1000,depth:1000,height:1000}};
let assets=[],selected=null,state=null,debounce=null;
async function loadData(){try{assets=(await (await fetch('../assets.json')).json()).assets}catch(e){assets=(await (await fetch('sample_data/sample_assets.json')).json()).assets}renderFilters();renderAssets();}
function renderFilters(){const types=[...new Set(assets.map(a=>a.elementType))].sort();typeFilter.innerHTML='<option value="">All element types</option>'+types.map(t=>`<option>${t}</option>`).join('')}
function renderAssets(){const q=search.value.toLowerCase(),t=typeFilter.value;assetList.innerHTML='';assets.filter(a=>(!t||a.elementType===t)&&a.displayName.toLowerCase().includes(q)).forEach(a=>{const d=document.createElement('div');d.className='asset'+(selected&&selected.id===a.id?' active':'');d.innerHTML=`<b>${a.displayName}</b><small>${a.elementType}</small><small>${a.category}</small>`;d.onclick=()=>selectAsset(a);assetList.appendChild(d)})}
function defaults(asset){const f=FALLBACKS[asset.elementType]||FALLBACKS.GenericBIMObject, p={};(asset.parameters||[]).forEach(x=>p[x.name]=x.default??f[x.name]??null);Object.entries(f).forEach(([k,v])=>{if(p[k]===undefined)p[k]=v});return p}
function selectAsset(asset){selected=asset;state={instanceId:'object_'+Date.now(),assetId:asset.id,elementType:asset.elementType,category:asset.category,parameters:defaults(asset),placement:{x:0,y:0,z:0,rotation:0},editability:asset.editability||{}};renderAssets();renderToolbar();draw();renderState()}
function groups(asset){if(asset.toolbar&&asset.toolbar.groups&&asset.toolbar.groups.length)return asset.toolbar.groups;const g={};(asset.parameters||[]).forEach(p=>(g[p.toolbarGroup||'general']??=[]).push(p.name));return Object.entries(g).map(([k,v])=>({groupId:k,label:k,parameters:v}))}
function renderToolbar(){toolbar.classList.remove('hidden');toolbarBody.innerHTML='';const byName=Object.fromEntries((selected.parameters||[]).map(p=>[p.name,p]));groups(selected).forEach(g=>{const wrap=document.createElement('div');wrap.className='group';wrap.innerHTML=`<h3>${g.label}</h3>`;(g.parameters||[]).forEach(n=>{const p=byName[n];if(!p)return;const field=document.createElement('div');field.className='field';const val=state.parameters[n]??'';let input=p.uiControl==='select'?`<select data-param="${n}">${(p.options||[]).map(o=>`<option ${o==val?'selected':''}>${o}</option>`).join('')}</select>`:p.uiControl==='checkbox'?`<input type="checkbox" data-param="${n}" ${val?'checked':''}>`:p.uiControl==='textarea'?`<textarea data-param="${n}">${val}</textarea>`:`<input type="${p.uiControl==='color_picker'?'color':p.uiControl==='number_input'?'number':'text'}" data-param="${n}" value="${val??''}">`;field.innerHTML=`<label>${p.label||n} ${p.unit?`(${p.unit})`:''}</label>${input}<div class="help">${p.description||''}${p.min!=null?' min '+p.min:''}${p.max!=null?' max '+p.max:''}</div><div class="error" id="err_${n}"></div>`;wrap.appendChild(field)});toolbarBody.appendChild(wrap)});toolbarBody.querySelectorAll('[data-param]').forEach(i=>i.oninput=()=>{clearTimeout(debounce);debounce=setTimeout(()=>update(i),180)})}
function validate(p,val){const e=[];if(p.uiControl==='number_input'){const n=Number(val);if(Number.isNaN(n))e.push('Must be numeric');if(p.validation&&p.validation.positive&&n<=0)e.push('Must be positive');if(p.min!=null&&n<Number(p.min))e.push('Below minimum');if(p.max!=null&&n>Number(p.max))e.push('Above maximum')}return e}
function update(input){const p=selected.parameters.find(x=>x.name===input.dataset.param);let v=input.type==='checkbox'?input.checked:input.value;if(input.type==='number')v=Number(v);const errs=validate(p,v);document.getElementById('err_'+p.name).textContent=errs.join(', ');if(!errs.length){state.parameters[p.name]=v;draw();renderState()}}
function draw(){const c=preview,ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.translate(390,280);ctx.strokeStyle='#1d3557';ctx.fillStyle='#8ecae6';const p=state.parameters,e=state.elementType;function box(w,h,d=60){ctx.fillRect(-w/2,-h/2,w,h);ctx.strokeRect(-w/2,-h/2,w,h);ctx.beginPath();ctx.moveTo(-w/2,-h/2);ctx.lineTo(-w/2+d,-h/2-d);ctx.lineTo(w/2+d,-h/2-d);ctx.lineTo(w/2,-h/2);ctx.stroke()} if(e==='Pipe'){ctx.beginPath();ctx.ellipse(0,0,(p.diameter||100)/2,60,0,0,7);ctx.fill();ctx.stroke()} else if(e==='Vegetation'){ctx.fillStyle='#8b5a2b';ctx.fillRect(-15,0,30,120);ctx.fillStyle='#3a7d44';ctx.beginPath();ctx.arc(0,-50,(p.diameter||1500)/20,0,7);ctx.fill();ctx.stroke()} else box(Math.min((p.width||p.length||1000)/5,500),Math.min((p.height||p.thickness||500)/5,420));ctx.restore()}
function renderState(){stateJson.textContent=JSON.stringify(state,null,2)}
downloadState.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=state.instanceId+'.json';a.click()};search.oninput=renderAssets;typeFilter.onchange=renderAssets;collapseBtn.onclick=()=>toolbar.classList.toggle('collapsed');let drag=false,ox=0,oy=0;toolbarHeader.onmousedown=e=>{drag=true;ox=e.clientX-toolbar.offsetLeft;oy=e.clientY-toolbar.offsetTop};document.onmouseup=()=>drag=false;document.onmousemove=e=>{if(drag){toolbar.style.left=e.clientX-ox+'px';toolbar.style.top=e.clientY-oy+'px'}};loadData();
